# Generated by Django 6.0.7 on 2026-08-10 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("team", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="Employment Type",
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "application_email",
                    models.EmailField(
                        default="careers@primekeyhomes.com",
                        max_length=254,
                        verbose_name="Application Email",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Job Opening",
                "verbose_name_plural": "Job Openings",
                "db_table": "careers_job_openings",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
