"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

import os
from pathlib import Path
from datetime import timedelta

import environ
from django.urls import reverse_lazy

from core.config_checks import validate_production_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(
    DEBUG=(bool, True),
    ALLOWED_HOSTS=(list, []),
    CORS_ALLOWED_ORIGINS=(list, ["http://localhost:3000", "http://127.0.0.1:3000"]),
    CORS_ALLOW_CREDENTIALS=(bool, True),
    REDIS_URL=(str, "redis://localhost:6379/0"),
    REDIS_CACHE_URL=(str, "redis://localhost:6379/1"),
    DJANGO_Q_REDIS_URL=(str, "redis://localhost:6379/2"),
    SECRET_KEY=(str, "django-insecure-dev-key-change-in-production"),
)

# Read .env file if it exists
environ.Env.read_env(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")

# Fail fast in production if critical security settings are left at insecure defaults
validate_production_settings(
    secret_key=SECRET_KEY,
    debug=DEBUG,
    allowed_hosts=ALLOWED_HOSTS,
)


# Application definition

INSTALLED_APPS = [
    # Third-party apps (must load before django.contrib.admin)
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    # Django core apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "drf_spectacular",
    "django_ratelimit",
    "django_q",
    "axes",
    # Local project apps
    "apps.crm",
    "apps.careers",
    "apps.properties",
    "apps.landlords",
    "apps.tenancy",
    "apps.compliance",
    "apps.ecommerce",
    "apps.otp_auth",
    "apps.dashboard",
    "apps.notifications",
    "apps.messaging",
    "apps.users",
    "apps.contact",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "core.middleware.TrustedProxyIPMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "axes.middleware.AxesMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.IdleSessionMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL"),
}


# Email (Contact Form Delivery)
# Dev: console backend prints emails to terminal
# Prod: switch to SMTP backend and fill in Hostinger credentials
EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = env("EMAIL_HOST", default="smtp.hostinger.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=465)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL", default="Primekey Homes <hello@primekeyhomesandpropertiesltd.com>"
)
CONTACT_RECIPIENT_EMAIL = env(
    "CONTACT_RECIPIENT_EMAIL", default="hello@primekeyhomesandpropertiesltd.com"
)

# OTP Providers: Resend (email) and Sendchamp (SMS)
# In dev, keys may be empty — OTP flow still works via dev_code (is_dev_client).
RESEND_API_KEY = env("RESEND_API_KEY", default="")
SENDCHAMP_API_KEY = env("SENDCHAMP_API_KEY", default="")
SENDCHAMP_SENDER_ID = env("SENDCHAMP_SENDER_ID", default="Primekey")
SENDCHAMP_ROUTE = env("SENDCHAMP_ROUTE", default="dnd")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# WhiteNoise serves staticfiles on Render (no nginx). Compression + caching enabled.
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "core" / "static",
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Protected storage for NDPR data exports (never served by nginx)
EXPORT_STORAGE_DIR = BASE_DIR / "exports"

# Protected storage for sensitive landlord documents (IDs, proof of ownership).
# Lives OUTSIDE MEDIA_ROOT so nginx/Django never serve it publicly; files are
# delivered only through the authenticated download endpoint.
PROTECTED_STORAGE_DIR = BASE_DIR / "protected"


CORS_ALLOWED_ORIGINS = env("CORS_ALLOWED_ORIGINS")
CORS_ALLOW_CREDENTIALS = env("CORS_ALLOW_CREDENTIALS")


# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Primekey Homes API",
    "DESCRIPTION": "Nigerian real estate platform API (Buyer, Landlord, Builder pathways).",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
}
if env.bool("SPECTACULAR_RESTRICT_DOCS", default=False):
    SPECTACULAR_SETTINGS["SERVE_PERMISSIONS"] = [
        "rest_framework.permissions.IsAdminUser",
    ]

# Rate limiting (django-ratelimit uses cache backend)
# Security-sensitive counters MUST NOT silently bypass when Redis is down.
# `default` is allowed to degrade (IGNORE_EXCEPTIONS=True) for general caching,
# but ratelimit/axes use a strict cache that fails closed (500) rather than
# silently disabling lockouts.
RATELIMIT_USE_CACHE = "axes"

# Redis Cache Configuration
REDIS_CACHE_URL = env("REDIS_CACHE_URL")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "IGNORE_EXCEPTIONS": True,
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "CONNECTION_POOL_KWARGS": {"protocol": 2},
        },
        "KEY_PREFIX": "primekey",
        "TIMEOUT": 300,
    },
    "sessions": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"protocol": 2},
        },
        "KEY_PREFIX": "primekey_session",
    },
    "axes": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # No IGNORE_EXCEPTIONS — brute-force counters must fail closed, not bypass
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "CONNECTION_POOL_KWARGS": {"protocol": 2},
        },
        "KEY_PREFIX": "primekey_axes",
        "TIMEOUT": 300,
    },
}

# Session engine using Redis
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "sessions"

# Session lifecycle hardening
SESSION_COOKIE_AGE = 60 * 60  # 1 hour absolute lifetime
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_SAVE_EVERY_REQUEST = True
SESSION_IDLE_TIMEOUT_SECONDS = 30 * 60  # 30 minutes of inactivity

# django-axes: brute-force lockout for session/admin login attempts
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_LOCKOUT_PARAMETERS = ["ip_address"]
AXES_CACHE = "axes"

# Django Q2 Configuration for background tasks
DJANGO_Q_REDIS_URL = env("DJANGO_Q_REDIS_URL")

Q_CLUSTER = {
    "name": "primekey",
    "workers": 4,
    "recycle": 500,
    "timeout": 60,
    "retry": 600,
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
    "redis": DJANGO_Q_REDIS_URL,
    "ack_failures": True,
    "max_attempts": 3,
    "catch_up": False,
    "sync": False,
    "monitor": True,
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": "primekey-homes-frontend",
    "ISSUER": "primekey-homes-api",
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_WINDOW_REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "SLIDING_WINDOW": False,
}

# Default auto field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Security settings for production
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)

if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# django-unfold admin theme — styled to match frontend Primekey Homes identity
UNFOLD = {
    "SITE_TITLE": "Primekey Homes Admin",
    "SITE_HEADER": "Primekey Homes",
    "SITE_SUBHEADER": "Backoffice",
    "SITE_URL": "/",
    "SITE_ICON": "admin/img/logo.svg",
    "SITE_ICON_WIDTH": 40,
    "SITE_ICON_HEIGHT": 40,
    "DASHBOARD_CALLBACK": "core.admin.dashboard_callback",
    "LOGIN": {
        "image": "admin/img/logo.svg",
    },
    "SHOW_HISTORY": True,
    "SHOW_NOTIFICATIONS": True,
    "STYLES": [
        "/static/admin/css/custom.css",
    ],
    "SCRIPTS": [
        "/static/admin/js/custom.js",
    ],
    "COLORS": {
        "primary": {
            "50": "245 247 250",       # #f5f7fa — Moon background
            "100": "232 235 241",      # #e8ebf1 — Moon surface
            "200": "163 185 240",      # #a3b9f0 — blue5
            "300": "105 145 242",      # #6991f2 — blue3
            "400": "76 122 240",       # #4c7af0 — blue2
            "500": "59 89 193",        # #3b59c1 — Moon primary blue
            "600": "47 84 167",        # #2f54a7 — blue1
            "700": "13 42 98",         # #0d2a62 — blue0 (navy)
            "800": "13 42 98",         # #0d2a62
            "900": "13 42 98",         # #0d2a62
        },
        "success": {
            "50": "236 246 246",
            "100": "217 238 238",
            "500": "65 166 181",       # #41a6b5 — Moon green
            "600": "65 166 181",
        },
        "warning": {
            "50": "255 244 237",
            "100": "255 233 218",
            "500": "255 150 108",      # #ff966c — Moon orange
            "600": "255 150 108",
        },
        "danger": {
            "50": "255 241 242",
            "100": "255 222 224",
            "500": "255 117 127",      # #ff757f — Moon red
            "600": "255 117 127",
        },
        "info": {
            "50": "231 249 252",
            "100": "204 243 249",
            "500": "13 185 215",       # #0db9d7 — Moon cyan
            "600": "13 185 215",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Operations",
                "separator": True,
                "items": [
                    {"title": "Dashboard", "icon": "dashboard", "link": reverse_lazy("admin:index")},
                    {"title": "Properties", "icon": "home_work", "link": reverse_lazy("admin:properties_property_changelist")},
                    {"title": "Concierge Leads", "icon": "support_agent", "link": reverse_lazy("admin:crm_conciergelead_changelist")},
                ],
            },
            {
                "title": "People",
                "items": [
                    {"title": "Users", "icon": "group", "link": reverse_lazy("admin:auth_user_changelist")},
                    {"title": "Groups", "icon": "workspaces", "link": reverse_lazy("admin:auth_group_changelist")},
                    {"title": "Agents", "icon": "badge", "link": reverse_lazy("admin:dashboard_agentprofile_changelist")},
                    {"title": "Landlords", "icon": "real_estate_agent", "link": reverse_lazy("admin:landlords_landlordprofile_changelist")},
                ],
            },
            {
                "title": "Compliance",
                "items": [
                    {"title": "Consent Logs", "icon": "verified_user", "link": reverse_lazy("admin:compliance_consentlog_changelist")},
                    {"title": "Export Requests", "icon": "download", "link": reverse_lazy("admin:compliance_exportrequest_changelist")},
                    {"title": "Erasure Requests", "icon": "delete", "link": reverse_lazy("admin:compliance_erasurerequest_changelist")},
                    {"title": "Anonymization Logs", "icon": "history_edu", "link": reverse_lazy("admin:compliance_anonymizationlog_changelist")},
                ],
            },
            {
                "title": "Communication",
                "items": [
                    {"title": "WhatsApp Threads", "icon": "chat", "link": reverse_lazy("admin:messaging_whatsappthread_changelist")},
                    {"title": "Notifications", "icon": "notifications", "link": reverse_lazy("admin:notifications_notification_changelist")},
                ],
            },
            {
                "title": "Careers",
                "items": [
                    {"title": "Job Openings", "icon": "work", "link": reverse_lazy("admin:careers_jobopening_changelist")},
                    {"title": "Applications", "icon": "assignment", "link": reverse_lazy("admin:careers_jobapplication_changelist")},
                ],
            },
            {
                "title": "Audit",
                "items": [
                    {"title": "Admin Logs", "icon": "history", "link": reverse_lazy("admin:admin_logentry_changelist")},
                ],
            },
        ],
    },
}