# Generated by Django 5.2.16 on 2026-08-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="recipient_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
