# Generated by Django 6.0.7 on 2026-08-10 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappthread",
            name="assigned_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whatsapp_threads",
                to="dashboard.agentprofile",
            ),
        ),
    ]
