# Generated by Django 5.2.16 on 2026-07-29 10:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('id_type', models.CharField(choices=[('nin', 'National ID (NIN)'), ('passport', 'International Passport'), ('driver_license', "Driver's License"), ('voter_card', "Permanent Voter's Card")], max_length=30, verbose_name='ID Type')),
                ('id_number', models.CharField(max_length=50, verbose_name='ID Number')),
                ('property_count', models.IntegerField(default=1, verbose_name='Number of Properties to List')),
                ('ndpr_consent', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landlord Profile',
                'verbose_name_plural': 'Landlord Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('tour_type', models.CharField(choices=[('in_person', 'In-Person'), ('virtual', 'Virtual')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='landlords.landlordprofile')),
            ],
            options={
                'verbose_name': 'Appointment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyIntake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Lagos', max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('toilets', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='landlords.landlordprofile')),
            ],
            options={
                'verbose_name': 'Property Intake',
                'verbose_name_plural': 'Property Intakes',
                'ordering': ['-created_at'],
            },
        ),
    ]
