# Generated by Django 5.2.16 on 2026-08-02 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landlords", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVault",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("title_deed", "Title Deed"),
                            ("certificate_of_occupancy", "Certificate of Occupancy"),
                            ("proof_of_ownership", "Proof of Ownership"),
                            ("government_id", "Government-issued ID"),
                            ("land_receipt", "Land Receipt / Agreement"),
                            ("other", "Other"),
                        ],
                        default="title_deed",
                        max_length=40,
                    ),
                ),
                ("file", models.FileField(upload_to="landlord_documents/")),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "intake",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="landlords.propertyintake",
                    ),
                ),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="landlords.landlordprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Vault Entry",
                "verbose_name_plural": "Document Vault Entries",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
