# Generated by Django 6.1 on 2026-09-25 08:27

import apps.landlords.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0003_landlordprofile_user_alter_documentvault_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentvault',
            name='file',
            field=models.FileField(storage=apps.landlords.models.ProtectedStorage(), upload_to=apps.landlords.models.document_upload_path),
        ),
    ]
