from decimal import Decimal
from django.core.management.base import BaseCommand
from apps.properties.models import Property

PROPERTIES = [
    {
        "title": "Luxury 3-Bedroom Apartment in Lekki",
        "description": "Modern 3-bedroom apartment with ensuite bathrooms, spacious living room, fitted kitchen, and balcony overlooking the Lekki skyline.",
        "property_type": "flat",
        "price": 450000000,
        "address": "12 Admiralty Road",
        "city": "Lagos",
        "state": "Lagos",
        "area": "Lekki Phase 1",
        "bedrooms": 3,
        "bathrooms": 3,
        "toilets": 3,
        "is_serviced": True,
        "is_furnished": True,
        "is_featured": True,
    },
    {
        "title": "Self-Contain Studio in Yaba",
        "description": "Cozy self-contain studio near University of Lagos. Perfect for students or young professionals.",
        "property_type": "self_contain",
        "price": 850000,
        "address": "7 Commercial Avenue",
        "city": "Lagos",
        "state": "Lagos",
        "area": "Yaba",
        "bedrooms": 1,
        "bathrooms": 1,
        "toilets": 1,
        "is_furnished": True,
    },
    {
        "title": "Bungalow in Ikeja GRA",
        "description": "Well-maintained bungalow on a quiet street in Ikeja GRA. 4 bedrooms, large compound with garden.",
        "property_type": "bungalow",
        "price": 280000000,
        "address": "15 Oba Elegushi Close",
        "city": "Lagos",
        "state": "Lagos",
        "area": "Ikeja GRA",
        "bedrooms": 4,
        "bathrooms": 4,
        "toilets": 5,
        "is_serviced": True,
        "is_furnished": True,
        "is_featured": True,
    },
    {
        "title": "Fully Detached Duplex in Banana Island",
        "description": "Stunning fully detached duplex with swimming pool, rooftop terrace, and 24/7 security.",
        "property_type": "fully_detached_duplex",
        "price": 950000000,
        "address": "3 Banana Island Road",
        "city": "Lagos",
        "state": "Lagos",
        "area": "Banana Island",
        "bedrooms": 5,
        "bathrooms": 6,
        "toilets": 6,
        "is_serviced": True,
        "is_furnished": True,
        "is_featured": True,
    },
    {
        "title": "Room & Parlour in Surulere",
        "description": "Affordable room and parlour self-contain in a quiet area of Surulere. Close to markets and transport.",
        "property_type": "room_and_parlour",
        "price": 2200000,
        "address": "8 Akinwunmi Street",
        "city": "Lagos",
        "state": "Lagos",
        "area": "Surulere",
        "bedrooms": 2,
        "bathrooms": 1,
        "toilets": 1,
        "is_furnished": False,
    },
    {
        "title": "Short Let Apartment in Victoria Island",
        "description": "Fully serviced short-let apartment in Victoria Island. Ideal for business travelers.",
        "property_type": "short_let",
        "price": 15000000,
        "address": "22 Ahmadu Bello Way",
        "city": "Lagos",
        "state": "Lagos",
        "area": "Victoria Island",
        "bedrooms": 2,
        "bathrooms": 2,
        "toilets": 2,
        "is_serviced": True,
        "is_furnished": True,
    },
    {
        "title": "Penthouse in Ikoyi",
        "description": "Top-floor penthouse with panoramic view of Lagos Lagoon. 4 bedrooms, private pool, gym access.",
        "property_type": "penthouse",
        "price": 720000000,
        "address": "5 Bourdillon Road",
        "city": "Lagos",
        "state": "Lagos",
        "area": "Ikoyi",
        "bedrooms": 4,
        "bathrooms": 4,
        "toilets": 4,
        "is_serviced": True,
        "is_furnished": True,
        "is_featured": True,
    },
    {
        "title": "Single Room in Mushin",
        "description": "Single room in a well-managed tenement building. Shared kitchen and bathroom facilities.",
        "property_type": "single_room",
        "price": 400000,
        "address": "25 Olusoji Street",
        "city": "Lagos",
        "state": "Lagos",
        "area": "Mushin",
        "bedrooms": 1,
        "bathrooms": 0,
        "toilets": 1,
        "is_furnished": False,
    },
    {
        "title": "Commercial Shop in Alaba Market",
        "description": "Prime commercial shop space in Alaba International Market. High foot traffic.",
        "property_type": "commercial",
        "price": 25000000,
        "address": "Alaba International Market Road",
        "city": "Lagos",
        "state": "Lagos",
        "area": "Alaba",
        "bedrooms": 0,
        "bathrooms": 1,
        "toilets": 1,
        "is_serviced": False,
        "is_furnished": False,
    },
    {
        "title": "Land in Ajah",
        "description": "500 sqm residential land in a developing area of Ajah. Good for investment or building.",
        "property_type": "land",
        "price": 75000000,
        "address": "Ajah-Lekki Expressway",
        "city": "Lagos",
        "state": "Lagos",
        "area": "Ajah",
        "bedrooms": 0,
        "bathrooms": 0,
        "toilets": 0,
        "is_serviced": False,
        "is_furnished": False,
    },
    {
        "title": "Maisonette in GRA Port Harcourt",
        "description": "Spacious 5-bedroom maisonette in GRA Port Harcourt. Serviced, with generator backup.",
        "property_type": "maisonette",
        "price": 320000000,
        "address": "10 Forces Avenue",
        "city": "Port Harcourt",
        "state": "Rivers",
        "area": "GRA Phase 1",
        "bedrooms": 5,
        "bathrooms": 5,
        "toilets": 5,
        "is_serviced": True,
        "is_furnished": True,
        "is_featured": True,
    },
    {
        "title": "Terraced Duplex in Asokoro",
        "description": "Beautifully finished terraced duplex in Abuja's prestigious Asokoro district.",
        "property_type": "terrace_duplex",
        "price": 400000000,
        "address": "28 Yakubu Pam Street",
        "city": "Abuja",
        "state": "FCT",
        "area": "Asokoro",
        "bedrooms": 4,
        "bathrooms": 4,
        "toilets": 4,
        "is_serviced": True,
        "is_furnished": True,
        "is_featured": True,
    },
]


class Command(BaseCommand):
    help = "Seeds the database with sample property listings for testing"

    def handle(self, *args, **options):
        if Property.objects.count() > 0:
            self.stdout.write(self.style.WARNING(
                f"Database already has {Property.objects.count()} properties. Deleting existing data..."
            ))
            Property.objects.all().delete()

        for data in PROPERTIES:
            Property.objects.create(**data)

        self.stdout.write(self.style.SUCCESS(
            f"Successfully seeded {len(PROPERTIES)} properties"
        ))
