# Generated by Django 6.0.7 on 2026-07-27 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("self_contain", "Self-Contain / Studio"),
                            ("room_and_parlour", "Room & Parlour Self-Contain"),
                            ("single_room", "Single Room / Tenement"),
                            ("bq", "Boys' Quarters (BQ)"),
                            ("short_let", "Short Let / Serviced Apartment"),
                            ("flat", "Standard Flat / Apartment"),
                            ("maisonette", "Maisonette"),
                            ("bungalow", "Bungalow"),
                            ("terrace_duplex", "Terraced Duplex / Townhouse"),
                            ("semi_detached_duplex", "Semi-Detached Duplex"),
                            ("fully_detached_duplex", "Fully Detached Duplex"),
                            ("penthouse", "Penthouse"),
                            ("mansion", "Mansion / Luxury Villa"),
                            ("land", "Residential / Commercial Land"),
                            ("commercial", "Shop / Office / Commercial Space"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="NGN", max_length=10)),
                ("is_negotiable", models.BooleanField(default=False)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(default="Lagos", max_length=100)),
                ("area", models.CharField(max_length=100)),
                ("bedrooms", models.IntegerField(default=1)),
                ("bathrooms", models.IntegerField(default=1)),
                ("toilets", models.IntegerField(default=1)),
                ("is_serviced", models.BooleanField(default=False)),
                ("is_furnished", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("under_contract", "Under Contract"),
                            ("rented", "Rented"),
                            ("sold", "Sold"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Properties",
                "db_table": "properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("caption", models.CharField(blank=True, max_length=150, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_images",
                "ordering": ["-is_primary", "created_at"],
            },
        ),
    ]
