# Generated by Django 6.0.7 on 2026-08-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("sale", "For Sale"),
                    ("rent", "For Rent"),
                    ("short_let", "Short Let"),
                ],
                db_index=True,
                default="sale",
                max_length=20,
                verbose_name="Listing Purpose",
            ),
        ),
    ]
