# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Qwen 2.5 Coder (Local)
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: Qwen 2.5 Coder (Local)
    provider: llama.cpp
    model: qwen2.5-coder
    apiKey: local-token
    apiBase: http://localhost:8080
  - name: qwen2.5-coder
    provider: llama.cpp
    model: qwen2.5-coder
    roles:
      - apply
      - autocomplete
      - chat
      - edit
    defaultCompletionOptions:
      contextLength: 200000
      maxTokens: 64000
    capabilities:
      - tool_use
      - image_input

tabAutocompleteModel:
  title: Qwen 2.5 Coder (Local)
  provider: llama.cpp
  model: qwen2.5-coder
  apiBase: http://localhost:8080
  apiKey: local-token