# Generated by Django 6.0.7 on 2026-07-29 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConciergeLead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="Full Name"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "preferred_location",
                    models.CharField(max_length=255, verbose_name="Target Location"),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("any", "Any Property Type"),
                            ("flat_apartment", "Flat / Apartment"),
                            ("house_duplex", "House / Duplex"),
                            ("land", "Land"),
                            ("commercial", "Commercial Space"),
                        ],
                        default="any",
                        max_length=50,
                    ),
                ),
                (
                    "budget_min",
                    models.BigIntegerField(default=0, verbose_name="Min Budget (NGN)"),
                ),
                (
                    "budget_max",
                    models.BigIntegerField(
                        default=500000000, verbose_name="Max Budget (NGN)"
                    ),
                ),
                (
                    "bedrooms",
                    models.CharField(
                        default="any", max_length=20, verbose_name="Bedrooms"
                    ),
                ),
                (
                    "ndpr_consent",
                    models.BooleanField(
                        default=False, verbose_name="NDPR Privacy Consent Given"
                    ),
                ),
                (
                    "consent_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="NDPR Consent Timestamp"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active_sla_queue", "Active SLA Queue"),
                            ("assigned", "Assigned to Agent"),
                            ("contacted", "Contacted"),
                            ("closed_won", "Closed (Matched)"),
                            ("closed_lost", "Closed (Unmatched)"),
                            ("erased_ndpr", "Erased / Closed (NDPR Request)"),
                        ],
                        db_index=True,
                        default="active_sla_queue",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Concierge Lead",
                "verbose_name_plural": "Concierge Leads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="crm_concier_status_664224_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CONSENT_GIVEN", "Consent Given"),
                            ("CONSENT_REVOKED", "Consent Revoked"),
                            ("ERASURE_REQUESTED", "Erasure Requested"),
                            ("ERASURE_COMPLETED", "Erasure Completed"),
                        ],
                        default="CONSENT_GIVEN",
                        max_length=30,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "consent_text",
                    models.TextField(
                        default="I consent to Primekey Homes processing my contact information under NDPR."
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consent_logs",
                        to="crm.conciergelead",
                    ),
                ),
            ],
            options={
                "db_table": "crm_consent_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
