# Generated by Django 5.2.16 on 2026-07-29 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciergeLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('preferred_location', models.CharField(max_length=255, verbose_name='Target Location')),
                ('property_type', models.CharField(choices=[('any', 'Any Property Type'), ('flat_apartment', 'Flat / Apartment'), ('house_duplex', 'House / Duplex'), ('land', 'Land'), ('commercial', 'Commercial Space')], default='any', max_length=50)),
                ('budget_min', models.BigIntegerField(default=0, verbose_name='Min Budget (NGN)')),
                ('budget_max', models.BigIntegerField(default=500000000, verbose_name='Max Budget (NGN)')),
                ('bedrooms', models.CharField(default='any', max_length=20, verbose_name='Bedrooms')),
                ('ndpr_consent', models.BooleanField(default=False, verbose_name='NDPR Privacy Consent Given')),
                ('consent_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='NDPR Consent Timestamp')),
                ('status', models.CharField(choices=[('active_sla_queue', 'Active SLA Queue'), ('assigned', 'Assigned to Agent'), ('contacted', 'Contacted'), ('closed_won', 'Closed (Matched)'), ('closed_lost', 'Closed (Unmatched)')], db_index=True, default='active_sla_queue', max_length=30)),
                ('lead_score', models.IntegerField(default=0, verbose_name='Lead Score')),
                ('sla_deadline', models.DateTimeField(blank=True, null=True, verbose_name='SLA Deadline (2 hours from creation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Agent')),
            ],
            options={
                'verbose_name': 'Concierge Lead',
                'verbose_name_plural': 'Concierge Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('consent_text', models.TextField(default='I consent to Primekey Homes processing my contact information under NDPR.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to='crm.conciergelead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_match_score', models.IntegerField(default=0)),
                ('location_match_score', models.IntegerField(default=0)),
                ('property_type_match_score', models.IntegerField(default=0)),
                ('bedrooms_match_score', models.IntegerField(default=0)),
                ('completeness_score', models.IntegerField(default=0)),
                ('urgency_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_breakdown', to='crm.conciergelead')),
            ],
            options={
                'verbose_name': 'Lead Score',
                'verbose_name_plural': 'Lead Scores',
            },
        ),
        migrations.CreateModel(
            name='SLAAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('warning', 'Warning (30 min remaining)'), ('breach', 'SLA Breached'), ('critical', 'Critical (1+ hour overdue)')], max_length=20)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_sla_alerts', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_alerts', to='crm.conciergelead')),
            ],
            options={
                'verbose_name': 'SLA Alert',
                'verbose_name_plural': 'SLA Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conciergelead',
            index=models.Index(fields=['status', 'created_at'], name='crm_concier_status_664224_idx'),
        ),
        migrations.AddIndex(
            model_name='conciergelead',
            index=models.Index(fields=['sla_deadline', 'status'], name='crm_concier_sla_dea_b49f18_idx'),
        ),
        migrations.AddIndex(
            model_name='slaalert',
            index=models.Index(fields=['lead', 'acknowledged'], name='crm_slaaler_lead_id_aefd51_idx'),
        ),
    ]
