# Generated by Django 5.2.16 on 2026-08-02 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conciergelead",
            name="assigned_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_concierge_leads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Agent",
            ),
        ),
        migrations.AddField(
            model_name="conciergelead",
            name="sla_breached_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="SLA Breach Timestamp"
            ),
        ),
        migrations.AddField(
            model_name="conciergelead",
            name="sla_deadline",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="2-Hour SLA Deadline"
            ),
        ),
        migrations.CreateModel(
            name="LeadScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("budget_match_score", models.PositiveSmallIntegerField(default=0)),
                ("location_match_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "property_type_match_score",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("bedrooms_match_score", models.PositiveSmallIntegerField(default=0)),
                ("completeness_score", models.PositiveSmallIntegerField(default=0)),
                ("urgency_score", models.PositiveSmallIntegerField(default=0)),
                ("total_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "tier",
                    models.CharField(
                        choices=[("HOT", "Hot"), ("WARM", "Warm"), ("COLD", "Cold")],
                        default="COLD",
                        max_length=5,
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_breakdown",
                        to="crm.conciergelead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Score",
                "verbose_name_plural": "Lead Scores",
            },
        ),
        migrations.CreateModel(
            name="SLAAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("warning", "Warning"), ("critical", "Critical")],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("acknowledged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_alerts",
                        to="crm.conciergelead",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Alert",
                "verbose_name_plural": "SLA Alerts",
                "ordering": ["-created_at"],
            },
        ),
    ]
