# Generated by Django 5.2.16 on 2026-08-02 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_conciergelead_assigned_agent_and_more"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conciergelead",
            name="inquiry_message",
            field=models.TextField(blank=True, verbose_name="Inquiry Message"),
        ),
        migrations.AddField(
            model_name="conciergelead",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiries",
                to="properties.property",
                verbose_name="Listing Inquired About",
            ),
        ),
    ]
