# Generated by Django 5.2.16 on 2026-08-01 23:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("code", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "Login / Sign In"),
                            ("register", "Registration Verification"),
                            ("password_reset", "Password Reset"),
                        ],
                        default="login",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "OTP Code",
                "verbose_name_plural": "OTP Codes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone", "purpose", "used"],
                        name="otp_auth_ot_phone_65300b_idx",
                    )
                ],
            },
        ),
    ]
