# Generated by Django 6.0.7 on 2026-08-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="code",
            field=models.CharField(
                help_text="SHA-256 hash of the 6-digit code", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="otpcode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("login", "Login / Sign In"),
                    ("register", "Registration Verification"),
                    ("password_reset", "Password Reset"),
                    ("agent_login", "Agent Login"),
                ],
                default="login",
                max_length=20,
            ),
        ),
    ]
