# Generated by Django 6.0.7 on 2026-08-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp_auth", "0002_alter_otpcode_code_alter_otpcode_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="code",
            field=models.CharField(
                help_text="Salted HMAC-SHA256 digest of the 6-digit code",
                max_length=128,
            ),
        ),
    ]
