# Generated by Django 5.2.16 on 2026-07-29 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErasureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified - Processing'), ('processing', 'Anonymizing Data'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected (Legal Hold)')], db_index=True, default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('records_erased', models.JSONField(blank=True, default=dict)),
                ('rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(blank=True, choices=[('legal_obligation', 'Legal Retention Requirement'), ('legal_claims', 'Active Legal Proceedings'), ('public_interest', 'Public Interest'), ('freedom_expression', 'Freedom of Expression')], max_length=50, null=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Data Erasure Request',
                'verbose_name_plural': 'Data Erasure Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified - Processing'), ('processing', 'Compiling Data'), ('completed', 'Ready for Download'), ('failed', 'Failed'), ('expired', 'Download Expired')], db_index=True, default='pending', max_length=20)),
                ('include_metadata', models.BooleanField(default=False, help_text='Include IP addresses, user agents, timestamps')),
                ('reason', models.TextField(blank=True, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('records_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Export Request',
                'verbose_name_plural': 'Data Export Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('purpose', models.CharField(choices=[('concierge_sourcing', 'Concierge Property Sourcing'), ('marketing_emails', 'Marketing Communications'), ('sms_notifications', 'SMS Notifications'), ('property_alerts', 'Property Alert Emails'), ('data_analytics', 'Usage Analytics'), ('third_party_sharing', 'Third Party Data Sharing')], db_index=True, max_length=50)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_text', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('legal_basis', models.CharField(choices=[('consent', 'Consent (Art 6(1)(a))'), ('contract', 'Contract Performance (Art 6(1)(b))'), ('legal_obligation', 'Legal Obligation (Art 6(1)(c))'), ('vital_interests', 'Vital Interests (Art 6(1)(d))'), ('public_task', 'Public Task (Art 6(1)(e))'), ('legitimate_interests', 'Legitimate Interests (Art 6(1)(f))')], default='consent', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('withdrawn', models.BooleanField(default=False)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consent Log',
                'verbose_name_plural': 'Consent Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose'], name='compliance__email_aaae98_idx'), models.Index(fields=['phone', 'purpose'], name='compliance__phone_197781_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnonymizationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_id', models.UUIDField(db_index=True)),
                ('lead_phone', models.CharField(db_index=True, max_length=20)),
                ('lead_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('fields_anonymized', models.JSONField(help_text='Dict of field_name: true for each anonymized field')),
                ('original_data_hash', models.CharField(help_text='SHA-256 hash of original PII for audit verification', max_length=64)),
                ('trigger', models.CharField(choices=[('erasure_request', 'User Erasure Request'), ('retention_policy', 'Automated Retention Policy (6 months)'), ('admin_action', 'Admin Manual Anonymization'), ('sla_breach', 'SLA Breach Cleanup')], max_length=30)),
                ('related_request_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anonymization Log',
                'verbose_name_plural': 'Anonymization Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trigger', 'created_at'], name='compliance__trigger_4e9078_idx')],
            },
        ),
    ]
