# Generated by Django 6.0.7 on 2026-08-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erasurerequest",
            name="verification_code",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash of the 6-digit code",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exportrequest",
            name="verification_code",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash of the 6-digit code",
                max_length=64,
                null=True,
            ),
        ),
    ]
