# Generated by Django 6.0.7 on 2026-08-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0002_alter_erasurerequest_verification_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erasurerequest",
            name="verification_code",
            field=models.CharField(
                blank=True,
                help_text="Salted HMAC-SHA256 hash of the 6-digit code",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exportrequest",
            name="verification_code",
            field=models.CharField(
                blank=True,
                help_text="Salted HMAC-SHA256 hash of the 6-digit code",
                max_length=128,
                null=True,
            ),
        ),
    ]
