# Generated by Django 6.1 on 2026-09-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_alter_erasurerequest_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrequest',
            name='export_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of export_payload, so a downloader can verify integrity', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='export_payload',
            field=models.TextField(blank=True, help_text='JSON export body. Cleared by purge_expired_exports after expires_at.', null=True),
        ),
    ]
